config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'pages/welcome'

  resources :articles  do
    resources :comments
  end

  root 'pages#welcome'
  get '/about', to: 'pages#about'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :comments, dependent: :destroy
  validates :title, presence: true, length: { minimum: 5 }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  http_basic_authenticate_with name: "dhh", password: "secret", except: [:index, :show]

  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def edit
    @article = Article.find(params[:id])

  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to articles_path
  end

  private
    def article_params
      params.require(:article).permit(:title, :text)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  http_basic_authenticate_with name: "dhh", password: "secret", only: :destroy

  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_url(@article)
  end

  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_url(@article)
  end

  private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def welcome
    @title = 'Hello world'
  end

  def about
    @title = 'This page about us'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_form.erb
<%= form_with model: @article, local: true do |form| %>

  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>

  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>

  <p>
    <%= form.submit %>
  </p>

<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<ul>
  <li>
    <%= link_to 'New article', new_article_url %>
  </li>
  <li>
    <%= link_to 'Main page', root_url%>
  </li>
</ul>

<% @articles.each do |article| %>
  <article>
    <b>Title article:</b> <%= article.title %>
    <p>
      <b>Text article:</b> <%= article.text %>
    </p>
    <ul>
      <li>
        <%= link_to 'Show this article', article_path(article) %>
      </li>
      <li>
        <%= link_to 'Edit this article', edit_article_path(article) %>
      </li>
      <li>
        <%= link_to 'Destroy this article',
                    article_path(article),
                    method: :delete,
                    data: { confirm: 'Are you sure?' }
        %>
      </li>
    </ul>
  </article>
  <hr>
<% end %>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_url %>

app/views/articles/show.html.erb
<p>
  This title: <%= @article.title %>
</p>

<p>
  This text: <%= @article.text %>
</p>

<h3>Comments</h3>
<%= render @article.comments %>

<h4>Create Comment</h4>
<%= render 'comments/form' %>

<%= link_to 'Show all articles', articles_url %>

app/views/comments/_comment.html.erb
<p>
  <b>Commenter:</b>
  <%= comment.commenter %>
</p>
<p>
  <b>Body:</b>
  <%= comment.body %>
</p>
<ul>
  <li>
    <%= link_to 'Delete this comment',
                [comment.article, comment],
                method: :delete,
                data: { confirm: 'Are you sure?' }
    %>
  </li>
</ul>
<hr>

app/views/comments/_form.html.erb
<%= form_with(model: [ @article, @article.comments.build ], local: true) do |form| %>
  <p>
    <%= form.label :commenter %>
    <br>
    <%= form.text_field :commenter %>
  </p>
  <p>
    <%= form.label :body %>
    <br>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestRuby</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/about.erb
<%= link_to "Link to welcome (root page)", root_url %>
<h1>
  <%=	@title %>
</h1>
<p>
  Title generate ruby and name title going from ruby controller pages
</p>

app/views/pages/welcome.html.erb
<ul>
  <li>
    <%= link_to 'Link to about', about_url %>
  </li>
  <li>
    <%= link_to 'My Blog', articles_url %>
  </li>
</ul>
<h1>
  <%= @title %>
</h1>
<p>
  Title generate ruby and name title going from ruby controller pages
</p>